### ISSUE TITLE
希望新增横向滚动条或者侧边栏能够拉伸的功能

### ISSUE THREAD

**Issue by jsonwu5** [jawil/github-extension#62]
![image](https://s1.ax1x.com/2018/08/14/P2pEuR.png)

如图，文件名字过长导致只显示了一半，建议新增横向滚动条或者侧边栏可拉伸。
控制台看了下样式，其中的`overflow: hidden;`改成`overflow: auto;`会好些。

```CSS
.side-bar-main li {
    position: relative;
    cursor: pointer;
    line-height: 22px;
    max-height: 22px;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-size: 14px;
    padding-left: 1em;
    list-style: none;
    overflow: hidden;
    transition: all 0.5s ease-out;
}
```
